name: app_atletica
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  carousel_slider: ^5.0.0
  image_picker: ^1.1.2
  http: ^1.4.0
  intl: ^0.20.2
  google_fonts: ^6.2.1
  mask_text_input_formatter: ^2.9.0
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.2.6
  provider: ^6.1.5
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/aaabe.png
    - assets/images/brasao.png
    - assets/images/cartao_branco.png
    - assets/images/cartao.png
    - assets/images/emblema.png
    - assets/images/caneca.png
    - assets/images/roupa1.png
    - assets/images/roupa2.png
    - assets/images/camisetaa_masculina.png
    - assets/images/camiseta_feminina_1.png
    - assets/images/caneca_oficial.png
    - assets/images/bone.jpeg
    - assets/images/caneca_estampa_premium.jpeg
    - assets/images/caneca_personalizada.jpeg
    - assets/images/chaveiro.jpeg
    - assets/images/tatuagens_temporarias.jpeg
    - assets/images/selfieCarteirinha.png
  fonts:
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-VariableFont_wght.ttf
